name: Push

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Update format
        run: cargo fmt
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v2.4.0
        with:
          commit_message: Format files
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    needs: update
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Init
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libncurses5-dev
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy --verbose
      - name: Test
        run: cargo test --verbose
      
  publish:
    if: startsWith(github.ref, 'refs/tags')
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
