name: Push

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update format
      run: cargo fmt
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v2.4.0
      with:
        commit_message: Format files
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  validate:
    needs: update
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
