name: Push

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Check format
      run: cargo fmt --verbose -- --check
    - name: Lint
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
